import type { Metadata } from "next";

import { dir } from "i18next";

import "../globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { Header } from "./components/header";
import { Provider } from "./components/provider";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  const { lng } = await params;

  return (
    <html dir={dir(lng)} lang={lng}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Header lng={lng} />
          <main className="p-4">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
